/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Auth API
 * API DOCUMENTATION
 * OpenAPI spec version: 1.0
 */
export interface CreateExchangeRateDto {
  rate: number;
  bank_name: string;
}

export interface PaginationMeta {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface CreateExchangeRateDtoPaginatedResponse {
  data: CreateExchangeRateDto[];
  meta: PaginationMeta;
}

export interface UpdateExchangeRateDto {
  rate?: number;
  bank_name?: string;
}

export interface CreateProductTypeDto {
  name: string;
}

export interface CreateProductTypeDtoPaginatedResponse {
  data: CreateProductTypeDto[];
  meta: PaginationMeta;
}

export interface UpdateProductTypeDto {
  name?: string;
}

export type Unit = typeof Unit[keyof typeof Unit];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Unit = {
  PIECE: 'PIECE',
  METER: 'METER',
  SQUAREMETER: 'SQUAREMETER',
  KILOGRAMM: 'KILOGRAMM',
} as const;

export interface CreateProductVariantDto {
  name: string;
  type: string;
  unit: Unit;
}

export interface CreateProductVariantDtoPaginatedResponse {
  data: CreateProductVariantDto[];
  meta: PaginationMeta;
}

export interface UpdateProductVariantDto {
  name?: string;
  type?: string;
  unit?: Unit;
}

export interface CreateContactDto {
  name: string;
  phone: string;
}

export interface CreateContactDtoPaginatedResponse {
  data: CreateContactDto[];
  meta: PaginationMeta;
}

export interface UpdateContactDto {
  name?: string;
  phone?: string;
}

export type ExchangeRateControllerFindAllParams = {
/**
 * Page number (starting from 1)
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
};

export type ProductTypeControllerFindAllParams = {
/**
 * Page number (starting from 1)
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
};

export type ProductVariantControllerFindAllParams = {
/**
 * Page number (starting from 1)
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
};

export type ContactControllerFindAllParams = {
/**
 * Page number (starting from 1)
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
};

