/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Auth API
 * API DOCUMENTATION
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ContactControllerFindAllParams,
  CreateContactDto,
  CreateContactDtoPaginatedResponse,
  CreateExchangeRateDto,
  CreateExchangeRateDtoPaginatedResponse,
  CreateProductTypeDto,
  CreateProductTypeDtoPaginatedResponse,
  CreateProductVariantDto,
  CreateProductVariantDtoPaginatedResponse,
  ExchangeRateControllerFindAllParams,
  ProductTypeControllerFindAllParams,
  ProductVariantControllerFindAllParams,
  UpdateContactDto,
  UpdateExchangeRateDto,
  UpdateProductTypeDto,
  UpdateProductVariantDto
} from './api.schemas';

import { customFetch } from '../utils/apiFetch';




export const appControllerGetHello = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/`, method: 'GET', signal
    },
      );
    }
  

export const getAppControllerGetHelloQueryKey = () => {
    return [`/`] as const;
    }

    
export const getAppControllerGetHelloQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHello>>> = ({ signal }) => appControllerGetHello(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppControllerGetHelloQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
export type AppControllerGetHelloQueryError = unknown


export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetHelloQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create ExchangeRate
 */
export const exchangeRateControllerCreate = (
    createExchangeRateDto: CreateExchangeRateDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateExchangeRateDto>(
      {url: `/exchange-rate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createExchangeRateDto, signal
    },
      );
    }
  


export const getExchangeRateControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerCreate>>, TError,{data: CreateExchangeRateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerCreate>>, TError,{data: CreateExchangeRateDto}, TContext> => {

const mutationKey = ['exchangeRateControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exchangeRateControllerCreate>>, {data: CreateExchangeRateDto}> = (props) => {
          const {data} = props ?? {};

          return  exchangeRateControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ExchangeRateControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof exchangeRateControllerCreate>>>
    export type ExchangeRateControllerCreateMutationBody = CreateExchangeRateDto
    export type ExchangeRateControllerCreateMutationError = unknown

    /**
 * @summary Create ExchangeRate
 */
export const useExchangeRateControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerCreate>>, TError,{data: CreateExchangeRateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exchangeRateControllerCreate>>,
        TError,
        {data: CreateExchangeRateDto},
        TContext
      > => {

      const mutationOptions = getExchangeRateControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get all ExchangeRate
 */
export const exchangeRateControllerFindAll = (
    params?: ExchangeRateControllerFindAllParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateExchangeRateDtoPaginatedResponse>(
      {url: `/exchange-rate`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getExchangeRateControllerFindAllQueryKey = (params?: ExchangeRateControllerFindAllParams,) => {
    return [`/exchange-rate`, ...(params ? [params]: [])] as const;
    }

    
export const getExchangeRateControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError = unknown>(params?: ExchangeRateControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExchangeRateControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>> = ({ signal }) => exchangeRateControllerFindAll(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExchangeRateControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>>
export type ExchangeRateControllerFindAllQueryError = unknown


export function useExchangeRateControllerFindAll<TData = Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError = unknown>(
 params: undefined |  ExchangeRateControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exchangeRateControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof exchangeRateControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExchangeRateControllerFindAll<TData = Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError = unknown>(
 params?: ExchangeRateControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exchangeRateControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof exchangeRateControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExchangeRateControllerFindAll<TData = Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError = unknown>(
 params?: ExchangeRateControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all ExchangeRate
 */

export function useExchangeRateControllerFindAll<TData = Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError = unknown>(
 params?: ExchangeRateControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExchangeRateControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update ExchangeRate by ID
 */
export const exchangeRateControllerUpdate = (
    updateExchangeRateDto: UpdateExchangeRateDto,
 ) => {
      
      
      return customFetch<CreateExchangeRateDto>(
      {url: `/exchange-rate`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateExchangeRateDto
    },
      );
    }
  


export const getExchangeRateControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerUpdate>>, TError,{data: UpdateExchangeRateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerUpdate>>, TError,{data: UpdateExchangeRateDto}, TContext> => {

const mutationKey = ['exchangeRateControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exchangeRateControllerUpdate>>, {data: UpdateExchangeRateDto}> = (props) => {
          const {data} = props ?? {};

          return  exchangeRateControllerUpdate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ExchangeRateControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof exchangeRateControllerUpdate>>>
    export type ExchangeRateControllerUpdateMutationBody = UpdateExchangeRateDto
    export type ExchangeRateControllerUpdateMutationError = unknown

    /**
 * @summary Update ExchangeRate by ID
 */
export const useExchangeRateControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerUpdate>>, TError,{data: UpdateExchangeRateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exchangeRateControllerUpdate>>,
        TError,
        {data: UpdateExchangeRateDto},
        TContext
      > => {

      const mutationOptions = getExchangeRateControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get ExchangeRate by ID
 */
export const exchangeRateControllerFindOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateExchangeRateDto>(
      {url: `/exchange-rate/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getExchangeRateControllerFindOneQueryKey = (id: number,) => {
    return [`/exchange-rate/${id}`] as const;
    }

    
export const getExchangeRateControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExchangeRateControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>> = ({ signal }) => exchangeRateControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExchangeRateControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>>
export type ExchangeRateControllerFindOneQueryError = unknown


export function useExchangeRateControllerFindOne<TData = Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exchangeRateControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof exchangeRateControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExchangeRateControllerFindOne<TData = Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exchangeRateControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof exchangeRateControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExchangeRateControllerFindOne<TData = Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ExchangeRate by ID
 */

export function useExchangeRateControllerFindOne<TData = Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exchangeRateControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExchangeRateControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete entity by ID
 */
export const exchangeRateControllerRemove = (
    id: number,
 ) => {
      
      
      return customFetch<void>(
      {url: `/exchange-rate/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getExchangeRateControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerRemove>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['exchangeRateControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exchangeRateControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  exchangeRateControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ExchangeRateControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof exchangeRateControllerRemove>>>
    
    export type ExchangeRateControllerRemoveMutationError = unknown

    /**
 * @summary Delete entity by ID
 */
export const useExchangeRateControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exchangeRateControllerRemove>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exchangeRateControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getExchangeRateControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create ProductType
 */
export const productTypeControllerCreate = (
    createProductTypeDto: CreateProductTypeDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateProductTypeDto>(
      {url: `/product-type`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProductTypeDto, signal
    },
      );
    }
  


export const getProductTypeControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerCreate>>, TError,{data: CreateProductTypeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerCreate>>, TError,{data: CreateProductTypeDto}, TContext> => {

const mutationKey = ['productTypeControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productTypeControllerCreate>>, {data: CreateProductTypeDto}> = (props) => {
          const {data} = props ?? {};

          return  productTypeControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductTypeControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof productTypeControllerCreate>>>
    export type ProductTypeControllerCreateMutationBody = CreateProductTypeDto
    export type ProductTypeControllerCreateMutationError = unknown

    /**
 * @summary Create ProductType
 */
export const useProductTypeControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerCreate>>, TError,{data: CreateProductTypeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productTypeControllerCreate>>,
        TError,
        {data: CreateProductTypeDto},
        TContext
      > => {

      const mutationOptions = getProductTypeControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get all ProductType
 */
export const productTypeControllerFindAll = (
    params?: ProductTypeControllerFindAllParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateProductTypeDtoPaginatedResponse>(
      {url: `/product-type`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getProductTypeControllerFindAllQueryKey = (params?: ProductTypeControllerFindAllParams,) => {
    return [`/product-type`, ...(params ? [params]: [])] as const;
    }

    
export const getProductTypeControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError = unknown>(params?: ProductTypeControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductTypeControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productTypeControllerFindAll>>> = ({ signal }) => productTypeControllerFindAll(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductTypeControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof productTypeControllerFindAll>>>
export type ProductTypeControllerFindAllQueryError = unknown


export function useProductTypeControllerFindAll<TData = Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError = unknown>(
 params: undefined |  ProductTypeControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productTypeControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof productTypeControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductTypeControllerFindAll<TData = Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError = unknown>(
 params?: ProductTypeControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productTypeControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof productTypeControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductTypeControllerFindAll<TData = Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError = unknown>(
 params?: ProductTypeControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all ProductType
 */

export function useProductTypeControllerFindAll<TData = Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError = unknown>(
 params?: ProductTypeControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductTypeControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update ProductType by ID
 */
export const productTypeControllerUpdate = (
    updateProductTypeDto: UpdateProductTypeDto,
 ) => {
      
      
      return customFetch<CreateProductTypeDto>(
      {url: `/product-type`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProductTypeDto
    },
      );
    }
  


export const getProductTypeControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerUpdate>>, TError,{data: UpdateProductTypeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerUpdate>>, TError,{data: UpdateProductTypeDto}, TContext> => {

const mutationKey = ['productTypeControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productTypeControllerUpdate>>, {data: UpdateProductTypeDto}> = (props) => {
          const {data} = props ?? {};

          return  productTypeControllerUpdate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductTypeControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof productTypeControllerUpdate>>>
    export type ProductTypeControllerUpdateMutationBody = UpdateProductTypeDto
    export type ProductTypeControllerUpdateMutationError = unknown

    /**
 * @summary Update ProductType by ID
 */
export const useProductTypeControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerUpdate>>, TError,{data: UpdateProductTypeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productTypeControllerUpdate>>,
        TError,
        {data: UpdateProductTypeDto},
        TContext
      > => {

      const mutationOptions = getProductTypeControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get ProductType by ID
 */
export const productTypeControllerFindOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateProductTypeDto>(
      {url: `/product-type/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getProductTypeControllerFindOneQueryKey = (id: number,) => {
    return [`/product-type/${id}`] as const;
    }

    
export const getProductTypeControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductTypeControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productTypeControllerFindOne>>> = ({ signal }) => productTypeControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductTypeControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof productTypeControllerFindOne>>>
export type ProductTypeControllerFindOneQueryError = unknown


export function useProductTypeControllerFindOne<TData = Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productTypeControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof productTypeControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductTypeControllerFindOne<TData = Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productTypeControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof productTypeControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductTypeControllerFindOne<TData = Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ProductType by ID
 */

export function useProductTypeControllerFindOne<TData = Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productTypeControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductTypeControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete entity by ID
 */
export const productTypeControllerRemove = (
    id: number,
 ) => {
      
      
      return customFetch<void>(
      {url: `/product-type/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getProductTypeControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerRemove>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['productTypeControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productTypeControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  productTypeControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductTypeControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof productTypeControllerRemove>>>
    
    export type ProductTypeControllerRemoveMutationError = unknown

    /**
 * @summary Delete entity by ID
 */
export const useProductTypeControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productTypeControllerRemove>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productTypeControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getProductTypeControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create ProductVariant
 */
export const productVariantControllerCreate = (
    createProductVariantDto: CreateProductVariantDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateProductVariantDto>(
      {url: `/product-variant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProductVariantDto, signal
    },
      );
    }
  


export const getProductVariantControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerCreate>>, TError,{data: CreateProductVariantDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerCreate>>, TError,{data: CreateProductVariantDto}, TContext> => {

const mutationKey = ['productVariantControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productVariantControllerCreate>>, {data: CreateProductVariantDto}> = (props) => {
          const {data} = props ?? {};

          return  productVariantControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductVariantControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof productVariantControllerCreate>>>
    export type ProductVariantControllerCreateMutationBody = CreateProductVariantDto
    export type ProductVariantControllerCreateMutationError = unknown

    /**
 * @summary Create ProductVariant
 */
export const useProductVariantControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerCreate>>, TError,{data: CreateProductVariantDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productVariantControllerCreate>>,
        TError,
        {data: CreateProductVariantDto},
        TContext
      > => {

      const mutationOptions = getProductVariantControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get all ProductVariant
 */
export const productVariantControllerFindAll = (
    params?: ProductVariantControllerFindAllParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateProductVariantDtoPaginatedResponse>(
      {url: `/product-variant`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getProductVariantControllerFindAllQueryKey = (params?: ProductVariantControllerFindAllParams,) => {
    return [`/product-variant`, ...(params ? [params]: [])] as const;
    }

    
export const getProductVariantControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError = unknown>(params?: ProductVariantControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductVariantControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productVariantControllerFindAll>>> = ({ signal }) => productVariantControllerFindAll(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductVariantControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof productVariantControllerFindAll>>>
export type ProductVariantControllerFindAllQueryError = unknown


export function useProductVariantControllerFindAll<TData = Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError = unknown>(
 params: undefined |  ProductVariantControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productVariantControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof productVariantControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductVariantControllerFindAll<TData = Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError = unknown>(
 params?: ProductVariantControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productVariantControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof productVariantControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductVariantControllerFindAll<TData = Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError = unknown>(
 params?: ProductVariantControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all ProductVariant
 */

export function useProductVariantControllerFindAll<TData = Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError = unknown>(
 params?: ProductVariantControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductVariantControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update ProductVariant by ID
 */
export const productVariantControllerUpdate = (
    updateProductVariantDto: UpdateProductVariantDto,
 ) => {
      
      
      return customFetch<CreateProductVariantDto>(
      {url: `/product-variant`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProductVariantDto
    },
      );
    }
  


export const getProductVariantControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerUpdate>>, TError,{data: UpdateProductVariantDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerUpdate>>, TError,{data: UpdateProductVariantDto}, TContext> => {

const mutationKey = ['productVariantControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productVariantControllerUpdate>>, {data: UpdateProductVariantDto}> = (props) => {
          const {data} = props ?? {};

          return  productVariantControllerUpdate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductVariantControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof productVariantControllerUpdate>>>
    export type ProductVariantControllerUpdateMutationBody = UpdateProductVariantDto
    export type ProductVariantControllerUpdateMutationError = unknown

    /**
 * @summary Update ProductVariant by ID
 */
export const useProductVariantControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerUpdate>>, TError,{data: UpdateProductVariantDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productVariantControllerUpdate>>,
        TError,
        {data: UpdateProductVariantDto},
        TContext
      > => {

      const mutationOptions = getProductVariantControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get ProductVariant by ID
 */
export const productVariantControllerFindOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateProductVariantDto>(
      {url: `/product-variant/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getProductVariantControllerFindOneQueryKey = (id: number,) => {
    return [`/product-variant/${id}`] as const;
    }

    
export const getProductVariantControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductVariantControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productVariantControllerFindOne>>> = ({ signal }) => productVariantControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductVariantControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof productVariantControllerFindOne>>>
export type ProductVariantControllerFindOneQueryError = unknown


export function useProductVariantControllerFindOne<TData = Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productVariantControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof productVariantControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductVariantControllerFindOne<TData = Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productVariantControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof productVariantControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductVariantControllerFindOne<TData = Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ProductVariant by ID
 */

export function useProductVariantControllerFindOne<TData = Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productVariantControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductVariantControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete entity by ID
 */
export const productVariantControllerRemove = (
    id: number,
 ) => {
      
      
      return customFetch<void>(
      {url: `/product-variant/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getProductVariantControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerRemove>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['productVariantControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productVariantControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  productVariantControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductVariantControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof productVariantControllerRemove>>>
    
    export type ProductVariantControllerRemoveMutationError = unknown

    /**
 * @summary Delete entity by ID
 */
export const useProductVariantControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productVariantControllerRemove>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productVariantControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getProductVariantControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create Contact
 */
export const contactControllerCreate = (
    createContactDto: CreateContactDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateContactDto>(
      {url: `/contact`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContactDto, signal
    },
      );
    }
  


export const getContactControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerCreate>>, TError,{data: CreateContactDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contactControllerCreate>>, TError,{data: CreateContactDto}, TContext> => {

const mutationKey = ['contactControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contactControllerCreate>>, {data: CreateContactDto}> = (props) => {
          const {data} = props ?? {};

          return  contactControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ContactControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof contactControllerCreate>>>
    export type ContactControllerCreateMutationBody = CreateContactDto
    export type ContactControllerCreateMutationError = unknown

    /**
 * @summary Create Contact
 */
export const useContactControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerCreate>>, TError,{data: CreateContactDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contactControllerCreate>>,
        TError,
        {data: CreateContactDto},
        TContext
      > => {

      const mutationOptions = getContactControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get all Contact
 */
export const contactControllerFindAll = (
    params?: ContactControllerFindAllParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateContactDtoPaginatedResponse>(
      {url: `/contact`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getContactControllerFindAllQueryKey = (params?: ContactControllerFindAllParams,) => {
    return [`/contact`, ...(params ? [params]: [])] as const;
    }

    
export const getContactControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof contactControllerFindAll>>, TError = unknown>(params?: ContactControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContactControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof contactControllerFindAll>>> = ({ signal }) => contactControllerFindAll(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContactControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof contactControllerFindAll>>>
export type ContactControllerFindAllQueryError = unknown


export function useContactControllerFindAll<TData = Awaited<ReturnType<typeof contactControllerFindAll>>, TError = unknown>(
 params: undefined |  ContactControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContactControllerFindAll<TData = Awaited<ReturnType<typeof contactControllerFindAll>>, TError = unknown>(
 params?: ContactControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContactControllerFindAll<TData = Awaited<ReturnType<typeof contactControllerFindAll>>, TError = unknown>(
 params?: ContactControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all Contact
 */

export function useContactControllerFindAll<TData = Awaited<ReturnType<typeof contactControllerFindAll>>, TError = unknown>(
 params?: ContactControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContactControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Contact by ID
 */
export const contactControllerUpdate = (
    updateContactDto: UpdateContactDto,
 ) => {
      
      
      return customFetch<CreateContactDto>(
      {url: `/contact`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateContactDto
    },
      );
    }
  


export const getContactControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerUpdate>>, TError,{data: UpdateContactDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contactControllerUpdate>>, TError,{data: UpdateContactDto}, TContext> => {

const mutationKey = ['contactControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contactControllerUpdate>>, {data: UpdateContactDto}> = (props) => {
          const {data} = props ?? {};

          return  contactControllerUpdate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ContactControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof contactControllerUpdate>>>
    export type ContactControllerUpdateMutationBody = UpdateContactDto
    export type ContactControllerUpdateMutationError = unknown

    /**
 * @summary Update Contact by ID
 */
export const useContactControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerUpdate>>, TError,{data: UpdateContactDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contactControllerUpdate>>,
        TError,
        {data: UpdateContactDto},
        TContext
      > => {

      const mutationOptions = getContactControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get Contact by ID
 */
export const contactControllerFindOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateContactDto>(
      {url: `/contact/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getContactControllerFindOneQueryKey = (id: number,) => {
    return [`/contact/${id}`] as const;
    }

    
export const getContactControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof contactControllerFindOne>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContactControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof contactControllerFindOne>>> = ({ signal }) => contactControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContactControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof contactControllerFindOne>>>
export type ContactControllerFindOneQueryError = unknown


export function useContactControllerFindOne<TData = Awaited<ReturnType<typeof contactControllerFindOne>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContactControllerFindOne<TData = Awaited<ReturnType<typeof contactControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContactControllerFindOne<TData = Awaited<ReturnType<typeof contactControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Contact by ID
 */

export function useContactControllerFindOne<TData = Awaited<ReturnType<typeof contactControllerFindOne>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contactControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContactControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete entity by ID
 */
export const contactControllerRemove = (
    id: number,
 ) => {
      
      
      return customFetch<void>(
      {url: `/contact/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getContactControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerRemove>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contactControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['contactControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contactControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  contactControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ContactControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof contactControllerRemove>>>
    
    export type ContactControllerRemoveMutationError = unknown

    /**
 * @summary Delete entity by ID
 */
export const useContactControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactControllerRemove>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contactControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getContactControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
